<a href="https://colab.research.google.com/github/grjadhav409/Entropy-prediction-ML/blob/main/2_1_descriptors_mordred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install 'mordred[full]'  # install with extra requires

!pip install rdkit-pypi

import pandas as pd

from multiprocessing import freeze_support

from rdkit import Chem

from mordred import Calculator, descriptors

Collecting mordred[full]
  Downloading mordred-1.2.0.tar.gz (128 kB)
     |████████████████████████████████| 128 kB 8.4 MB/s
Requirement already satisfied: six==1.* in /usr/local/lib/python3.7/dist-packages (from mordred[full]) (1.15.0)
Requirement already satisfied: numpy==1.* in /usr/local/lib/python3.7/dist-packages (from mordred[full]) (1.21.6)
Requirement already satisfied: networkx==2.* in /usr/local/lib/python3.7/dist-packages (from mordred[full]) (2.6.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from mordred[full]) (1.3.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from mordred[full]) (4.64.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->mordred[full]) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->mordred[full]) (2022.1)
Building wheels for collected packages: mordred
  Building wheel for mordred (setup.py) ... done
  Created wheel for mordred: filename=mordred-1.2.0-py3-none-any.whl size=176725 sha256=e16be48fa5ab5807eb556b7a0387c6e111ae7eea826e1fea45b96d0fd109d7aa
  Stored in directory: /root/.cache/pip/wheels/02/c0/2e/e7e3d63b431777712ebc128bc4deb9ac5cb19afc7c1ea341ec
Successfully built mordred
Installing collected packages: mordred
Successfully installed mordred-1.2.0
Collecting rdkit-pypi
  Downloading rdkit_pypi-2022.3.1.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (22.5 MB)
     |████████████████████████████████| 22.5 MB 1.4 MB/s
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi) (7.1.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi) (1.21.6)
Installing collected packages: rdkit-pypi
Successfully installed rdkit-pypi-2022.3.1.1

In [ ]:
conda install -c rdkit

SyntaxError: ignored

In [ ]:
from rdkit.Chem import AllChem as Chem
Chem.MolToSmiles(Chem.MolFromSLN('N[1](CH2CH2CH2C@1=O)CH3'))
'CN1CCCC1=O'

ModuleNotFoundError: ignored

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/physical property predictions/entropy/entropy_data/df_smiles.csv")

In [ ]:
df

,name,cid,isomeric_smiles,charge,species,hfg
0,Decane,15600,CCCCCCCCCC,0,C10H22,-249.70
1,Decane,15600,CCCCCCCCCC,0,C10H22,-249.70
2,Decane,15600,CCCCCCCCCC,0,C10H22,-249.70
3,Decane,15600,CCCCCCCCCC,0,C10H22,-249.70
4,Decane,15600,CCCCCCCCCC,0,C10H22,-249.70
...,...,...,...,...,...,...
1851,Diiodomethane,6346,C(I)I,0,CH2I2,118.00
1852,Aziridine,9033,C1CN1,0,C2H5N,126.00
1853,Cyclobutanecarbonitrile,78148,C1CC(C1)C#N,0,C5H7N,147.30
1854,Fluorene,6853,C1C2=CC=CC=C2C3=CC=CC=C31,0,C13H10,176.70
1855,Succinonitrile,8062,C(CC#N)C#N,0,C4H4N2,209.66

In [ ]:
df1 = df.drop_duplicates()

In [ ]:
df1

,name,cid,isomeric_smiles,charge,species,hfg
0,Decane,15600,CCCCCCCCCC,0,C10H22,-249.70
9,Nonane,8141,CCCCCCCCC,0,C9H20,-228.30
18,tetramethylbutane,11675,CC(C)(C)C(C)(C)C,0,(CH3)3CC(CH3)3,-226.20
27,Octane,356,CCCCCCCC,0,C8H18,-208.40
36,2-methylhexane,11582,CCCCC(C)C,0,C7H16,-195.00
...,...,...,...,...,...,...
1851,Diiodomethane,6346,C(I)I,0,CH2I2,118.00
1852,Aziridine,9033,C1CN1,0,C2H5N,126.00
1853,Cyclobutanecarbonitrile,78148,C1CC(C1)C#N,0,C5H7N,147.30
1854,Fluorene,6853,C1C2=CC=CC=C2C3=CC=CC=C31,0,C13H10,176.70
1855,Succinonitrile,8062,C(CC#N)C#N,0,C4H4N2,209.66

In [ ]:
name = df1['isomeric_smiles'].tolist()
molecules =[]
for i in name:
  molecules.append(Chem.MolFromSmiles(i))
if __name__ == "__main__":
    freeze_support()
    # Create Calculator
    calc = Calculator(descriptors)
df2= pd.DataFrame(data=calc.pandas(molecules))
df2

NameError: ignored

In [ ]:
df1.reset_index(drop=True, inplace=True)
df2.reset_index(drop=True, inplace=True)

In [ ]:
extracted_col_name= df1["name"]
extracted_col_hfg= df1["hfg"]
df2.insert(0, "name", extracted_col_name)
df2 = df2.join(extracted_col_hfg)
df2

,name,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,...,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2,hfg
0,Decane,6.363961,6.254644,0,0,12.053348,1.918986,3.837972,12.053348,1.205335,...,35.643477,142.172151,4.442880,165,7,34.0,32.0,4.0,2.750000,-249.70
1,Nonane,5.656854,5.715477,0,0,10.627503,1.902113,3.804226,10.627503,1.180834,...,33.969149,128.156501,4.419190,120,6,30.0,28.0,3.75,2.500000,-228.30
2,tetramethylbutane,5.808525,6.167293,0,0,7.211103,2.302776,4.605551,7.211103,0.901388,...,36.999431,114.140851,4.390033,58,9,38.0,40.0,6.125,1.562500,-226.20
3,Octane,4.949747,5.143137,0,0,9.517541,1.879385,3.75877,9.517541,1.189693,...,32.187603,114.140851,4.390033,84,5,26.0,24.0,3.5,2.250000,-208.40
4,2-methylhexane,4.461420,4.736714,0,0,7.727407,1.931852,3.863703,7.727407,1.103915,...,31.336140,100.125201,4.353270,52,4,24.0,22.0,3.861111,1.833333,-195.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,Diiodomethane,1.414214,1.414214,0,0,2.828427,1.414214,2.828427,2.828427,0.942809,...,17.310771,267.824596,53.564919,4,0,6.0,4.0,2.25,1.000000,118.00
404,Aziridine,2.121320,0.000000,0,1,4.0,2.0,3.0,4.0,1.333333,...,41.046721,43.042199,5.380275,3,0,12.0,12.0,0.75,0.750000,126.00
405,Cyclobutanecarbonitrile,4.242641,4.429961,0,0,6.60272,2.175328,4.350655,6.60272,1.100453,...,33.219913,81.057849,6.235219,29,3,26.0,28.0,2.111111,1.500000,147.30
406,Fluorene,10.485281,8.835388,0,0,17.90589,2.468694,4.747108,17.90589,1.377376,...,59.273430,166.078250,7.220793,219,19,72.0,87.0,2.694444,2.833333,176.70
407,Succinonitrile,3.535534,3.869735,0,0,6.987918,1.801938,3.603875,6.987918,1.164653,...,28.105124,80.037448,8.003745,35,3,18.0,16.0,3.0,1.750000,209.66

In [ ]:
/content/drive/MyDrive/Colab Notebooks/physical property predictions/entropy/entropy_data