<a href="https://colab.research.google.com/github/grjadhav409/Entropy-prediction-ML/blob/main/2_desriptors_calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# deepchem

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## lib

In [ ]:
!pip install deepchem
!pip install git+https://github.com/mordred-descriptor/mordred
!pip install rdkit-pypi
!pip install pubchempy


import deepchem as dc
import numpy as np
import pandas as pd

Collecting deepchem
  Downloading deepchem-2.6.1-py3-none-any.whl (608 kB)
     |████████████████████████████████| 608 kB 16.6 MB/s
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.3.5)
Collecting rdkit-pypi
  Downloading rdkit_pypi-2022.3.1.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (22.5 MB)
     |████████████████████████████████| 22.5 MB 1.1 MB/s
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.1.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.4.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->deepchem) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->deepchem) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->deepchem) (1.15.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi->deepchem) (7.1.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->deepchem) (3.1.0)
Installing collected packages: rdkit-pypi, deepchem
Successfully installed deepchem-2.6.1 rdkit-pypi-2022.3.1.1
Collecting git+https://github.com/mordred-descriptor/mordred
  Cloning https://github.com/mordred-descriptor/mordred to /tmp/pip-req-build-iwhq9i7o
  Running command git clone -q https://github.com/mordred-descriptor/mordred /tmp/pip-req-build-iwhq9i7o
Requirement already satisfied: six==1.* in /usr/local/lib/python3.7/dist-packages (from mordred==1.2.0) (1.15.0)
Requirement already satisfied: numpy==1.* in /usr/local/lib/python3.7/dist-packages (from mordred==1.2.0) (1.21.6)
Requirement already satisfied: networkx==2.* in /usr/local/lib/python3.7/dist-packages (from mordred==1.2.0) (2.6.3)
Building wheels for collected packages: mordred
  Building wheel for mordred (setup.py) ... done
  Created wheel for mordred: filename=mordred-1.2.0-py3-none-any.whl size=177700 sha256=15647ffeb20069d9616086d1f606196a26d5ccc05396413dcc1d165c2a3cea44
  Stored in directory: /tmp/pip-ephem-wheel-cache-hozppr71/wheels/23/ba/54/7121909af62418bda56701656ffbec9c5d7c289a8c120bdd4d
Successfully built mordred
Installing collected packages: mordred
Successfully installed mordred-1.2.0
Requirement already satisfied: rdkit-pypi in /usr/local/lib/python3.7/dist-packages (2022.3.1.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi) (7.1.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi) (1.21.6)
Collecting pubchempy
  Downloading PubChemPy-1.0.4.tar.gz (29 kB)
Building wheels for collected packages: pubchempy
  Building wheel for pubchempy (setup.py) ... done
  Created wheel for pubchempy: filename=PubChemPy-1.0.4-py3-none-any.whl size=13834 sha256=a5845d48a95aeb76c4b33e1109f29aafa482d66889f359d0a1c5057c5f6a6ea3
  Stored in directory: /root/.cache/pip/wheels/7c/3d/8c/8192697412e9899dc55bbbb08bbc1197bef333caaa2a71c448
Successfully built pubchempy
Installing collected packages: pubchempy
Successfully installed pubchempy-1.0.4

## data import

In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv("/content/drive/MyDrive/Colab Notebooks/physical property predictions/entropy/entropy_data/df_smiles.csv")

In [ ]:
df

     Unnamed: 0                   name  Entropy                         SMILES
0             3      Difluorodisulfane -336.440                           FSSF
1             4  chlorinepentafluoride -238.490                F[Cl](F)(F)(F)F
2             6   2,4-Cyclohexadienone  -70.000                   O=C1CC=CC=C1
3             7            Ozone anion  -61.130                       [O]O[O-]
4            11   Magnesium dichloride   39.233             [Mg++].[Cl-].[Cl-]
..          ...                    ...      ...                            ...
506         661             Octasulfur  430.310                     S1SSSSSSS1
507         662                 Octane  467.060                       CCCCCCCC
508         664                 Nonane  506.500                      CCCCCCCCC
509         665       Triphenylmethane  541.000  c1ccc(cc1)C(c2ccccc2)c3ccccc3
510         666                 Decane  545.800                     CCCCCCCCCC

[511 rows x 4 columns]

In [ ]:
df2 = df.drop(df.index[[1, 123, 233 ,300,302,303,302,304,305,306,301,307,363,435,473]])

## discriptor calculations

In [ ]:
smiles1 = df2['SMILES'].tolist()

In [ ]:
#smiles1

In [ ]:
#featurizer = dc.feat.CircularFingerprint(size=1024)
#featurizer = dc.feat.MACCSKeysFingerprint()
#featurizer=dc.feat.ConvMolFeaturizer(per_atom_fragmentation=False)
featurizer = dc.feat.PubChemFingerprint() #required rdkit and pubchempy installed
#featurizer = dc.feat.RDKitDescriptors()
#featurizer = dc.feat.MordredDescriptors(ignore_3D=True)


discriptors = featurizer.featurize(smiles1)

Failed to featurize datapoint 35, [H-].[Mg+]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 44, [SiH3]. Appending empty array
Exception message: 'PUGREST.Timeout'
Failed to featurize datapoint 59, [Be+].[F-]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 77, BCl. Appending empty array
Exception message: 'PUGREST.Timeout'
Failed to featurize datapoint 78, [Al+2].[H-].[H-]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 83, [AlH2+].[F-]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 88, [Be+].[OH-]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 90, [Be+].[Cl-]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 100, [F-].[Mg+]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 112, [Mg+][Mg][Mg+].[N-]=[N-]. Appending empty array
Exception message: 'PUGREST.BadRequest: error: '
Failed to featurize datapoint 118, [F-].[SiH2+]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 124, [AlH2+].[Cl-]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 126, O=[Si]=O. Appending empty array
Exception message: 'PUGREST.BadRequest: error: '
Failed to featurize datapoint 128, FBr. Appending empty array
Exception message: <urlopen error [Errno 99] Cannot assign requested address>
Failed to featurize datapoint 129, [O]O. Appending empty array
Exception message: Remote end closed connection without response
Failed to featurize datapoint 130, [Li+].[Li+].[OH-]. Appending empty array
Exception message: 'PUGREST.BadRequest: error: '
Failed to featurize datapoint 133, [Ca+].[F-]. Appending empty array
Exception message: 'PUGREST.BadRequest: error: '
Failed to featurize datapoint 134, [Cl-].[Na+]. Appending empty array
Exception message: 'PUGREST.BadRequest: error: '
Failed to featurize datapoint 136, [AlH2]S. Appending empty array
Exception message: <urlopen error [Errno 99] Cannot assign requested address>
Failed to featurize datapoint 138, C#CF. Appending empty array
Exception message: 'PUGREST.BadRequest: error: '
Failed to featurize datapoint 142, [Mg+2].[OH-].[OH-]. Appending empty array
Exception message: <urlopen error [Errno 99] Cannot assign requested address>
Failed to featurize datapoint 143, [CH]=C. Appending empty array
Exception message: 'PUGREST.BadRequest: error: '
Failed to featurize datapoint 145, [Cl-].[Mg+]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 150, [F-].[GeH2+]. Appending empty array
Exception message: 'PUGREST.BadRequest: error: '
Failed to featurize datapoint 175, [Ca+].[OH-]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 179, [AlH2+].[Br-]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 186, [Ca+].[Cl-]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 223, [Br-].[Ca+]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 230, [F-].[F-].[SiH2+2]. Appending empty array
Exception message: 'NoneType' object is not subscriptable
Failed to featurize datapoint 300, None. Appending empty array
Exception message: Python argument types in
    rdkit.Chem.rdmolfiles.CanonicalRankAtoms(NoneType)
did not match C++ signature:
    CanonicalRankAtoms(RDKit::ROMol mol, bool breakTies=True, bool includeChirality=True, bool includeIsotopes=True)
Failed to featurize datapoint 347, F[S](F)F. Appending empty array
Exception message: 'PUGREST.BadRequest: error: '
Failed to featurize datapoint 404, O=C1CCCC1. Appending empty array
Exception message: 'PUGREST.BadRequest: error: '
/usr/local/lib/python3.7/dist-packages/deepchem/feat/base_classes.py:305: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.asarray(features)

In [ ]:
X_rdkit = pd.DataFrame(data=discriptors)
X_rdkit.columns=["a"]
X_rdkit

                                                     a
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, ...
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, ...
..                                                 ...
492  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
493  [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...
494  [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...
495  [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, ...
496  [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, ...

[497 rows x 1 columns]

In [ ]:
x_pubchem=X_rdkit.a.str.split(pat=',',expand=True)

x_pubchem

      0
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
..   ..
492 NaN
493 NaN
494 NaN
495 NaN
496 NaN

[497 rows x 1 columns]

In [ ]:
y_entropy = df['Entropy']
y_entropy

0     -336.440
1     -238.490
2      -70.000
3      -61.130
4       39.233
        ...
506    430.310
507    467.060
508    506.500
509    541.000
510    545.800
Name: Entropy, Length: 511, dtype: float64

In [ ]:
X_rdkit.to_csv('X_rdkit.csv')
!cp X_rdkit.csv "/content/drive/MyDrive/Colab Notebooks/physical property predictions/entropy/entropy_data"

In [ ]:
y_entropy.to_csv('y_entropy.csv')
#!cp y_entropy.csv "/cont"